onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/NODE_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/RF_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/N_LOCAL_REGS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/N_REMOTE_LINES
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/AGGREGATE_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/FIFO_DEPTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/EN_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/WS_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/REQ_ARB_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/RSP_ARB_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/req_in_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/rsp_in_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/req_out_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/rsp_out_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/sampled_req_in
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/local_rx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/root_rx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/overflow_rx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/empty_rx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/req_rx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/pop_rx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/pop_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/empty_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/req_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_empty_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_rsp_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_pop_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_empty_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_rsp_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_pop_tx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_pop_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_empty_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_rsp_arb_in
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/en_rsp_arb_out
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_pop_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_empty_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_rsp_arb_in
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/ws_rsp_arb_out
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/remote_empty
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/remote_req
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/remote_pop
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/local_empty
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/local_rsp
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/local_pop
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/local_pop_q
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d /tb_bfm/i_dut_fractal_sync_1d/local_pop_d
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/COMB_IN}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/SD_MASK}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/FIFO_DEPTH}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/FIFO_COMB_OUT}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/clk_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/rst_ni}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/req_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/sampled_req_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/local_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/root_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/error_overflow_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/empty_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/req_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/pop_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/en_sample}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/sampled_sync}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/propagate}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/push}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/full_fifo}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[0]/i_rx/sampled_out_req}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/COMB_IN}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/SD_MASK}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/FIFO_DEPTH}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/FIFO_COMB_OUT}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/clk_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/rst_ni}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/req_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/sampled_req_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/local_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/root_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/error_overflow_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/empty_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/req_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/pop_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/en_sample}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/sampled_sync}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/propagate}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/push}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/full_fifo}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx} {/tb_bfm/i_dut_fractal_sync_1d/gen_rx[1]/i_rx/sampled_out_req}
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/SEL_IDX_W
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/pop_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/empty_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/element_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/element_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/req_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/gnt_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/pending_req
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/c_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/n_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/clear_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/out_en
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_rx_arb /tb_bfm/i_dut_fractal_sync_1d/i_rx_arb/sel_idx
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/COMB_IN}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/FIFO_DEPTH}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/FIFO_COMB_OUT}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/clk_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/rst_ni}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/rsp_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_error_overflow_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_error_overflow_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_empty_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_rsp_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_pop_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_empty_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_rsp_o}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_pop_i}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_sample}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_full_fifo}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_full_fifo}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/sampled_rsp}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/sampled_out_rsp}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_push_q}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_push_q}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/en_push_d}
add wave -noupdate -expand -group {sim:/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx} {/tb_bfm/i_dut_fractal_sync_1d/gen_tx[0]/i_tx/ws_push_d}
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/SEL_IDX_W
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/pop_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/empty_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/element_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/element_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/req_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/gnt_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/pending_req
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/c_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/n_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/clear_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/out_en
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_en_tx_arb/sel_idx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/SEL_IDX_W
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/pop_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/empty_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/element_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/element_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/req_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/gnt_arb
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/pending_req
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/c_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/n_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/clear_mask
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/out_en
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb /tb_bfm/i_dut_fractal_sync_1d/i_ws_tx_arb/sel_idx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/NODE_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/RF_DIM
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/RF_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_LOCAL_REGS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_REMOTE_LINES
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/AGGREGATE_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_RX_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_TX_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_FIFOS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/FIFO_DEPTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/EN_REMOTE_RF
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/LEVEL_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/SD_MASK
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/N_1D_RX_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/req_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/local_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/root_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/error_overflow_rx_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/error_overflow_tx_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/local_empty_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/local_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/local_pop_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/remote_empty_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/remote_req_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/remote_pop_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/detected_error_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/level
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_level
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_level
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/id
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_id
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_id
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/local_rsp
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/remote_req
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/id_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_id_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_id_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/sig_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_sig_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_sig_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/rf_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/empty_local_fifo_err
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/full_local_fifo_err
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/empty_remote_fifo_err
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/full_remote_fifo_err
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/fifo_error
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/check_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_check_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_check_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/check_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_check_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_check_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/bypass_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_bypass_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_bypass_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/bypass_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_bypass_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_bypass_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/present_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_present_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_present_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/present_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/h_present_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/v_present_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/push_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/full_local
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/push_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/full_remote
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/c_state
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc /tb_bfm/i_dut_fractal_sync_1d/i_cc/n_state
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/REMOTE_RF_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/EN_REMOTE_RF
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/N_LOCAL_REGS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/LEVEL_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/N_REMOTE_LINES
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/N_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/level_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/id_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/check_local_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/check_remote_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/present_local_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/present_remote_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/id_err_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/sig_err_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/bypass_local_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/bypass_remote_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/ignore_local_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/ignore_remote_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/N_REGS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/N_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/LOCAL_ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/MAX_ID
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/id_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/check_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/present_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/id_err_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/bypass_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/ignore_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/local_id
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/valid_idx
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/i_local_rf/check_rf
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/RF_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/LEVEL_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/N_CAM_LINES
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/N_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/LOCAL_ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/N_DM_REGS
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/SIG_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/MAX_SIG
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/MAX_LVL_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/LVL_LOOKUP_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/MAX_LOOKUP_LVL_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/LVL_SIG_LOOKUP
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/level_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/id_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/check_i
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/present_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/sig_err_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/bypass_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/ignore_o
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/local_id
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/lvl_sig
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/sig
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/local_sig
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/valid_sig
add wave -noupdate -expand -group sim:/tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf /tb_bfm/i_dut_fractal_sync_1d/i_cc/gen_1d_rf/i_rf/gen_1d_remote_rf/i_remote_rf/check_rf
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {32 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 160
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {996 ns}
