onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/TOP_NODE_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/RF_TYPE_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_LOCAL_REGS_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_REMOTE_LINES_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/RF_TYPE_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_LOCAL_REGS_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_REMOTE_LINES_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_LINKS_IN
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_LINKS_ITL
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_LINKS_OUT
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/AGGREGATE_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/LVL_OFFSET
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_1D_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_1D_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_NBR_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_NBR_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_2D_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/N_2D_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/h_1d_fsync_req_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/h_1d_fsync_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/v_1d_fsync_req_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/v_1d_fsync_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/h_nbr_fsycn_req_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/h_nbr_fsycn_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/v_nbr_fsycn_req_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/v_nbr_fsycn_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/h_2d_fsync_req_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/h_2d_fsync_rsp_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/v_2d_fsync_req_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut /tb_bfm/gen_dut_2x2/i_sync_network_dut/v_2d_fsync_rsp_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/TOP_NODE_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/RF_TYPE_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_LOCAL_REGS_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_REMOTE_LINES_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/RF_TYPE_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_LOCAL_REGS_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_REMOTE_LINES_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_LINKS_IN
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_LINKS_ITL
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_LINKS_OUT
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/AGGREGATE_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/LVL_OFFSET
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_1D_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_1D_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/OUT_LVL_OFFSET
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_1D_H_NODES
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_1D_V_NODES
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/ITL_AGGR_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/ITL_ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/FIFO_DEPTH_1D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/FIFO_DEPTH_2D
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_1D_NODE_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_1D_NODE_OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_H_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_V_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_NODE_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_H_OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_V_OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/N_2D_NODE_OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_1d_fsync_req_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_1d_fsync_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_1d_fsync_req_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_1d_fsync_rsp_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_2d_fsync_req_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_2d_fsync_rsp_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_2d_fsync_req_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_2d_fsync_rsp_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_1d_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_1d_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_1d_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_1d_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_tr_1d_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_tr_1d_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_1d_itl_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_1d_itl_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_1d_itl_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_1d_itl_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_2d_itl_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_2d_itl_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_2d_itl_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_2d_itl_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_2d_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/h_2d_fsync_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_2d_fsync_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2 /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/v_2d_fsync_rsp
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/NODE_TYPE}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/RF_TYPE}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/N_LOCAL_REGS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/N_REMOTE_LINES}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/AGGREGATE_WIDTH}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ID_WIDTH}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/LVL_OFFSET}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/FIFO_DEPTH}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/IN_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/OUT_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/EN_IN_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/WS_IN_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/REQ_ARB_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/RSP_ARB_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/clk_i}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/rst_ni}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/req_in_i}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/rsp_in_o}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/req_out_o}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/rsp_out_i}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/sampled_req_in}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/check_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/local_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/root_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/overflow_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/empty_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/req_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/pop_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/pop_req_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/empty_req_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/req_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/sampled_rsp_out}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/check_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_propagate_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_propagate_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_overflow_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_overflow_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/overflow_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_empty_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_rsp_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_pop_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_empty_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_rsp_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_pop_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_pop_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_empty_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_rsp_arb_in}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/en_rsp_arb_out}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_pop_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_empty_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_rsp_arb_in}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/ws_rsp_arb_out}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/remote_empty}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/remote_req}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/remote_pop}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/local_empty}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/local_rsp}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/local_pop}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/local_pop_q}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_h_1d_nodes[0]/i_h_1d_node/local_pop_d}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/NODE_TYPE}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/RF_TYPE}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/N_LOCAL_REGS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/N_REMOTE_LINES}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/AGGREGATE_WIDTH}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ID_WIDTH}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/LVL_OFFSET}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/FIFO_DEPTH}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/IN_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/OUT_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/EN_IN_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/WS_IN_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/REQ_ARB_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/RSP_ARB_PORTS}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/clk_i}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/rst_ni}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/req_in_i}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/rsp_in_o}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/req_out_o}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/rsp_out_i}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/sampled_req_in}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/check_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/local_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/root_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/overflow_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/empty_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/req_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/pop_rx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/pop_req_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/empty_req_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/req_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/sampled_rsp_out}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/check_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_propagate_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_propagate_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_overflow_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_overflow_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/overflow_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_empty_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_rsp_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_pop_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_empty_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_rsp_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_pop_tx}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_pop_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_empty_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_rsp_arb_in}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/en_rsp_arb_out}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_pop_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_empty_rsp_arb}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_rsp_arb_in}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/ws_rsp_arb_out}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/remote_empty}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/remote_req}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/remote_pop}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/local_empty}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/local_rsp}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/local_pop}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/local_pop_q}
add wave -noupdate -expand -group {sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node} {/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/gen_v_1d_nodes[0]/i_v_1d_node/local_pop_d}
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/NODE_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/RF_TYPE
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/N_LOCAL_REGS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/N_REMOTE_LINES
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/AGGREGATE_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/ID_WIDTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/LVL_OFFSET
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/FIFO_DEPTH
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/IN_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/IN_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/OUT_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/OUT_H_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/OUT_V_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/H_EN_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/H_WS_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/V_EN_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/V_WS_IN_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/H_REQ_ARB_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/V_REQ_ARB_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/H_RSP_ARB_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/V_RSP_ARB_PORTS
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/clk_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/rst_ni
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_req_in_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_rsp_in_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_req_in_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_rsp_in_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_req_out_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_rsp_out_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_req_out_o
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_rsp_out_i
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_sampled_req_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_check_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_local_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_root_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_overflow_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_empty_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_req_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_pop_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_sampled_req_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_check_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_local_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_root_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_overflow_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_empty_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_req_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_pop_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_pop_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_empty_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_pop_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_empty_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_req_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_sampled_rsp_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_check_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_propagate_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_propagate_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_sampled_rsp_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_check_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_propagate_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_propagate_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_empty_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_rsp_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_pop_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_empty_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_rsp_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_pop_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_empty_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_rsp_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_pop_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_empty_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_rsp_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_pop_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_pop_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_empty_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_rsp_arb_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_en_rsp_arb_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_pop_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_empty_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_rsp_arb_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/h_ws_rsp_arb_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_pop_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_empty_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_rsp_arb_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_en_rsp_arb_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_pop_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_empty_rsp_arb
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_rsp_arb_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/v_ws_rsp_arb_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/sampled_req_in
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/check_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/local_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/root_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/overflow_rx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/sampled_rsp_out
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/check_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/en_propagate_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/ws_propagate_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/overflow_tx
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/remote_empty
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/remote_req
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/remote_pop
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/local_empty
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/local_rsp
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/local_pop
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/local_pop_q
add wave -noupdate -expand -group sim:/tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node /tb_bfm/gen_dut_2x2/i_sync_network_dut/i_fractal_sync_2x2/i_top_node/local_pop_d
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 211
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {973 ns}
